# flake8: noqa
from collections import OrderedDict

jsonschema = OrderedDict([('createPairResponse',
              OrderedDict([('type', 'object'),
                           ('required', ['address', 'id']),
                           ('properties',
                            OrderedDict([('address',
                                          OrderedDict([('type', 'string'),
                                                       ('pattern',
                                                        '^0x[0-9abcdefABCDEF]{40}$'),
                                                       ('description',
                                                        'Etherium address'),
                                                       ('example',
                                                        '0xe20df59ecc01ee28e3e794d64f37c6961bae495c')])),
                                         ('id',
                                          OrderedDict([('type', 'string'),
                                                       ('format', 'uuid'),
                                                       ('description',
                                                        'Pair ID'),
                                                       ('example',
                                                        'd4171a66-af9f-493b-a4d7-dec0fc0c9e85')]))]))])),
             ('createPairRequest',
              OrderedDict([('type', 'object'),
                           ('required', ['address', 'expired_at']),
                           ('properties',
                            OrderedDict([('expired_at',
                                          OrderedDict([('type', 'number'),
                                                       ('description',
                                                        'TX expire timestamp'),
                                                       ('example',
                                                        1509559133)])),
                                         ('address',
                                          OrderedDict([('type', 'string'),
                                                       ('pattern',
                                                        '^0x[0-9abcdefABCDEF]{40}$'),
                                                       ('description',
                                                        'Etherium address'),
                                                       ('example',
                                                        '0xe20df59ecc01ee28e3e794d64f37c6961bae495c')]))]))]))])
